name: Build Vue
on: [push]
permissions:
  # contents: read
  pages: write
  id-token: write
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue...
    steps:
    - uses: actions/checkout@v3
    - name: Build Vue
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm i run-p
    - run: npm run build
    - run: cp dist/index.html dist/404.html
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
      # Upload entire repository
        path: './dist'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1